version: '2'

services:
  puppetmaster:
    build: puppetmaster-image
    container_name: puppetmaster
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./root:/root
      - ./environments:/etc/puppetlabs/code/environments
    networks:
      - lan
    ports:
      - 8140:8140
  puppetagent_1:
    build: puppetagent-image
    container_name: puppetagent_1
    hostname: puppetagent_one
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - lan
  puppetagent_2:
    build: puppetagent-image
    container_name: puppetagent_2
    hostname: puppetagent_two
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - lan

networks:
  lan:
