version: '2'

services:
  puppetmaster:
    hostname: puppetmaster
    domainname: puppetmaster.local
    build: puppetmaster-image
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./root:/root
      - ./environments:/etc/puppetlabs/code/environments
    networks:
      - lan
    ports:
      - 8140:8140
  puppetagent:
    hostname: puppetagent
    domainname: puppetagent.local
    build: puppetagent-image
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    networks:
      - lan
  nexus:
    image: sonatype/nexus3:latest
    volumes:
        - ./data:/nexus-data
    networks:
      lan:
        aliases:
          - nexus.prd.ace
#        ipv4_address: 172.20.0.6
    ports:
      - 8081:8081
      - 8123:8123
      - 5000:5000
      - 18443:18443
networks:
  lan:
